version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: BISOL_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: energy_db
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  fastapi:
    build: .
    container_name: fastapi
    environment:
      DATABASE_URL: postgresql+asyncpg://BISOL_user:password@db:5432/energy_db
      REDIS_URL: redis://redis:6379
      PYTHONPATH: /app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
